"""
Trains the HydroMind AI energy-forecast model.

A RandomForestRegressor predicting a day's total_kwh from day-of-week,
month, growth stage, device-activity fraction, and outdoor temperature —
the same Pipeline/OneHotEncoder pattern as train.py, kept as a sibling
script rather than merged into it so the crop health/risk pipeline and the
energy pipeline stay independently retrainable.

PROTOTYPE NOTE: trained on synthetic data (see energy_dataset_generator.py).
Swap in a CSV of real metered daily consumption with the same columns and
re-run this script unchanged to retrain on real data.

Run from the backend/ directory (after generating the dataset):
    python -m ml_engine.energy_train
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

ML_DIR = Path(__file__).resolve().parent
DATASET_PATH = ML_DIR / "data" / "energy_dataset.csv"
MODELS_DIR = ML_DIR / "models"

CATEGORICAL_FEATURES = ["growth_stage"]
NUMERIC_FEATURES = ["day_of_week", "month", "active_devices_fraction", "outdoor_temp_proxy"]
FEATURE_COLUMNS = CATEGORICAL_FEATURES + NUMERIC_FEATURES


def _build_preprocessor() -> ColumnTransformer:
    return ColumnTransformer(
        transformers=[("categorical", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES)],
        remainder="passthrough",
    )


def train():
    if not DATASET_PATH.exists():
        print(f"Dataset not found at {DATASET_PATH}. Run `python -m ml_engine.energy_dataset_generator` first.")
        sys.exit(1)

    df = pd.read_csv(DATASET_PATH)
    X = df[FEATURE_COLUMNS]
    y = df["total_kwh"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

    pipeline = Pipeline(
        steps=[
            ("preprocess", _build_preprocessor()),
            ("model", RandomForestRegressor(n_estimators=250, max_depth=None, min_samples_leaf=2, random_state=7)),
        ]
    )
    pipeline.fit(X_train, y_train)
    pred = pipeline.predict(X_test)
    r2 = r2_score(y_test, pred)
    mae = mean_absolute_error(y_test, pred)

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(pipeline, MODELS_DIR / "energy_model.pkl")

    metadata = {
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "dataset_size": len(df),
        "train_size": len(X_train),
        "test_size": len(X_test),
        "feature_columns": FEATURE_COLUMNS,
        "model": {
            "type": "RandomForestRegressor",
            "n_estimators": 250,
            "max_depth": "None (fully grown)",
            "r2_score": round(float(r2), 4),
            "mean_absolute_error": round(float(mae), 2),
        },
        "note": (
            "Prototype energy forecast model trained on synthetic data generated by "
            "energy_dataset_generator.py. Retrain on real metered consumption history for production use."
        ),
    }
    with open(MODELS_DIR / "energy_metadata.json", "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"Trained on {len(X_train)} rows, tested on {len(X_test)} rows.")
    print(f"R^2: {r2:.4f} | MAE: {mae:.2f} kWh")
    print(f"Saved model to {MODELS_DIR / 'energy_model.pkl'}")


if __name__ == "__main__":
    train()
