"""
Trains the HydroMind AI prototype ML models on the synthetic dataset.

Two models are trained:
  - health_status classifier  (RandomForestClassifier) -> Ideal / Warning / Critical
  - risk_score regressor      (RandomForestRegressor)   -> 0-100

Both are wrapped in a scikit-learn Pipeline that includes preprocessing
(one-hot encoding of the categorical crop/method/stage columns), so the
saved .pkl files can be handed a raw feature dict at inference time without
the caller needing to know about encoding.

PROTOTYPE NOTE: trained on synthetic, rule-generated data (see
dataset_generator.py). Swap in a CSV of real farm sensor history with the
same columns and re-run this script unchanged to retrain on real data.

Run from the backend/ directory (after generating the dataset):
    python -m ml_engine.train
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

ML_DIR = Path(__file__).resolve().parent
DATASET_PATH = ML_DIR / "data" / "synthetic_dataset.csv"
MODELS_DIR = ML_DIR / "models"

CATEGORICAL_FEATURES = ["crop_type", "hydroponic_method", "growth_stage"]
NUMERIC_FEATURES = [
    "ph",
    "ec",
    "water_temperature",
    "air_temperature",
    "humidity",
    "water_level",
    "light_intensity",
    "light_hours",
    "days_after_planting",
]
FEATURE_COLUMNS = CATEGORICAL_FEATURES + NUMERIC_FEATURES


def _build_preprocessor() -> ColumnTransformer:
    return ColumnTransformer(
        transformers=[
            ("categorical", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
        ],
        remainder="passthrough",
    )


def train():
    if not DATASET_PATH.exists():
        print(f"Dataset not found at {DATASET_PATH}. Run `python -m ml_engine.dataset_generator` first.")
        sys.exit(1)

    df = pd.read_csv(DATASET_PATH)
    X = df[FEATURE_COLUMNS]
    y_health = df["health_status"]
    y_risk = df["risk_score"]

    X_train, X_test, y_health_train, y_health_test, y_risk_train, y_risk_test = train_test_split(
        X, y_health, y_risk, test_size=0.2, random_state=42, stratify=y_health
    )

    health_pipeline = Pipeline(
        steps=[
            ("preprocess", _build_preprocessor()),
            ("model", RandomForestClassifier(n_estimators=300, max_depth=None, min_samples_leaf=2, random_state=42)),
        ]
    )
    health_pipeline.fit(X_train, y_health_train)
    health_pred = health_pipeline.predict(X_test)
    health_accuracy = accuracy_score(y_health_test, health_pred)

    risk_pipeline = Pipeline(
        steps=[
            ("preprocess", _build_preprocessor()),
            ("model", RandomForestRegressor(n_estimators=300, max_depth=None, min_samples_leaf=2, random_state=42)),
        ]
    )
    risk_pipeline.fit(X_train, y_risk_train)
    risk_pred = risk_pipeline.predict(X_test)
    risk_r2 = r2_score(y_risk_test, risk_pred)
    risk_mae = mean_absolute_error(y_risk_test, risk_pred)

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(health_pipeline, MODELS_DIR / "health_model.pkl")
    joblib.dump(risk_pipeline, MODELS_DIR / "risk_model.pkl")

    metadata = {
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "dataset_size": len(df),
        "train_size": len(X_train),
        "test_size": len(X_test),
        "feature_columns": FEATURE_COLUMNS,
        "categorical_features": CATEGORICAL_FEATURES,
        "numeric_features": NUMERIC_FEATURES,
        "health_classes": sorted(y_health.unique().tolist()),
        "health_model": {
            "type": "RandomForestClassifier",
            "n_estimators": 300,
            "max_depth": "None (fully grown)",
            "accuracy": round(float(health_accuracy), 4),
        },
        "risk_model": {
            "type": "RandomForestRegressor",
            "n_estimators": 300,
            "max_depth": "None (fully grown)",
            "r2_score": round(float(risk_r2), 4),
            "mean_absolute_error": round(float(risk_mae), 2),
        },
        "note": (
            "Prototype models trained on synthetic hydroponic data generated by "
            "dataset_generator.py. Retrain on real farm sensor history for production use."
        ),
    }
    with open(MODELS_DIR / "metadata.json", "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"Trained on {len(X_train)} rows, tested on {len(X_test)} rows.")
    print(f"Health classifier accuracy: {health_accuracy:.4f}")
    print(f"Risk regressor R^2: {risk_r2:.4f} | MAE: {risk_mae:.2f}")
    print(f"\nSaved models to {MODELS_DIR}")


if __name__ == "__main__":
    train()
